### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by Overload02** [epsilonfive/VYSION#2]
I recently wanted to check out your shell there were no current releases on the git. so I decided to compile it myself but I was met with an array of errors. 
I tried fixing some of the code and ended with more errors. :(

**Comment by epsilonfive** [comment]
This is unfortunately missing the ASM files in the shell, so it won't build. I'll add those later. Also, keep in mind that this repository does not reflect the current state of the shell.

**Comment by Overload02** [comment]
When are you going to update the repository? 
Isn't v1.0 out already?

**Comment by epsilonfive** [comment]
I've just uploaded those files, sorry for the delay. I've been pretty busy over the last week.
